name: docker-works

on:
  schedule:
    # every 21:41 UTC
    - cron: "41 21 * * *"
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: repo/auto
          push: true
          tags: ghcr.io/${{ github.actor }}/gha-debug-docker/auto:latest
  chrome-check:
    runs-on: ubuntu-latest
    needs: chrome
    container:
      image: ghcr.io/${{ github.actor }}/gha-debug-docker/auto:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check docker image
        run: |
          pip3 list
      - name: run selenium
        run: |
          echo "H4sIAAAAAAACA3WPsW7CMBCGdz+Fmy5BIvbQrRIDIMTUsrBHSX0klvCdsc8Jefu6JRRVaqeT7v/uO/3PTzrFoFuLGnCQfuKe8EWIUyAnI5wBbXLSOk+B5QitCXaA8DtWP3v1Qc4Rqna6n2wmIcizJYxy9RCobZ8NcLgl5eLOqMaYugldcoBcFlXVQ2POEGPxP4JUxQZNS9cM3fR/vCrn89U8F2JmVQdZ0zP7+Kr1OI4qdUz+q0r2CciuGTxZNHXu/P14M6njel+/r992S1kYO2TYB5sTUAxXfvgvyXJu+Anzh2+nagEAAA==" | base64 -d | zcat > test.py
          python3 test.py
